Fixes 'undefined reference to _xtr_stats_MPI_update_*' in libcudampi* tracing libraries
Adds missing MPI statistics convenience library to libcudampitrace*.
Regroups _LIBADD and _CFLAGS variables for all MPI libraries.